/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTestimonialsRouteImport } from './routes/admin/testimonials'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminNavigationRouteImport } from './routes/admin/navigation'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminDiscountsRouteImport } from './routes/admin/discounts'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminContentRouteImport } from './routes/admin/content'
import { Route as AdminColorsRouteImport } from './routes/admin/colors'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as SiteTermsRouteImport } from './routes/_site/terms'
import { Route as SiteShippingRouteImport } from './routes/_site/shipping'
import { Route as SiteProductsRouteImport } from './routes/_site/products'
import { Route as SitePrivacyRouteImport } from './routes/_site/privacy'
import { Route as SiteFaqsRouteImport } from './routes/_site/faqs'
import { Route as SiteContactRouteImport } from './routes/_site/contact'
import { Route as SiteCheckoutRouteImport } from './routes/_site/checkout'
import { Route as SiteCategoriesRouteImport } from './routes/_site/categories'
import { Route as SiteCartRouteImport } from './routes/_site/cart'
import { Route as SiteAccountRouteImport } from './routes/_site/account'
import { Route as SiteAboutRouteImport } from './routes/_site/about'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNavigationRoute = AdminNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiscountsRoute = AdminDiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminColorsRoute = AdminColorsRouteImport.update({
  id: '/colors',
  path: '/colors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const SiteTermsRoute = SiteTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => SiteRoute,
} as any)
const SiteShippingRoute = SiteShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProductsRoute = SiteProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => SiteRoute,
} as any)
const SitePrivacyRoute = SitePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SiteRoute,
} as any)
const SiteFaqsRoute = SiteFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCheckoutRoute = SiteCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCategoriesRoute = SiteCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCartRoute = SiteCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAccountRoute = SiteAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/about': typeof SiteAboutRoute
  '/account': typeof SiteAccountRoute
  '/cart': typeof SiteCartRoute
  '/categories': typeof SiteCategoriesRoute
  '/checkout': typeof SiteCheckoutRoute
  '/contact': typeof SiteContactRoute
  '/faqs': typeof SiteFaqsRoute
  '/privacy': typeof SitePrivacyRoute
  '/products': typeof SiteProductsRoute
  '/shipping': typeof SiteShippingRoute
  '/terms': typeof SiteTermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/colors': typeof AdminColorsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/users': typeof AdminUsersRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRouteWithChildren
  '/about': typeof SiteAboutRoute
  '/account': typeof SiteAccountRoute
  '/cart': typeof SiteCartRoute
  '/categories': typeof SiteCategoriesRoute
  '/checkout': typeof SiteCheckoutRoute
  '/contact': typeof SiteContactRoute
  '/faqs': typeof SiteFaqsRoute
  '/privacy': typeof SitePrivacyRoute
  '/products': typeof SiteProductsRoute
  '/shipping': typeof SiteShippingRoute
  '/terms': typeof SiteTermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/colors': typeof AdminColorsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/': typeof SiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_site/about': typeof SiteAboutRoute
  '/_site/account': typeof SiteAccountRoute
  '/_site/cart': typeof SiteCartRoute
  '/_site/categories': typeof SiteCategoriesRoute
  '/_site/checkout': typeof SiteCheckoutRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/faqs': typeof SiteFaqsRoute
  '/_site/privacy': typeof SitePrivacyRoute
  '/_site/products': typeof SiteProductsRoute
  '/_site/shipping': typeof SiteShippingRoute
  '/_site/terms': typeof SiteTermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/colors': typeof AdminColorsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/_site/': typeof SiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/account'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/faqs'
    | '/privacy'
    | '/products'
    | '/shipping'
    | '/terms'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/colors'
    | '/admin/content'
    | '/admin/dashboard'
    | '/admin/discounts'
    | '/admin/login'
    | '/admin/navigation'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/profile'
    | '/admin/testimonials'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/about'
    | '/account'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/faqs'
    | '/privacy'
    | '/products'
    | '/shipping'
    | '/terms'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/colors'
    | '/admin/content'
    | '/admin/dashboard'
    | '/admin/discounts'
    | '/admin/login'
    | '/admin/navigation'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/profile'
    | '/admin/testimonials'
    | '/admin/users'
    | '/'
  id:
    | '__root__'
    | '/_site'
    | '/admin'
    | '/_site/about'
    | '/_site/account'
    | '/_site/cart'
    | '/_site/categories'
    | '/_site/checkout'
    | '/_site/contact'
    | '/_site/faqs'
    | '/_site/privacy'
    | '/_site/products'
    | '/_site/shipping'
    | '/_site/terms'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/colors'
    | '/admin/content'
    | '/admin/dashboard'
    | '/admin/discounts'
    | '/admin/login'
    | '/admin/navigation'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/profile'
    | '/admin/testimonials'
    | '/admin/users'
    | '/_site/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/navigation': {
      id: '/admin/navigation'
      path: '/navigation'
      fullPath: '/admin/navigation'
      preLoaderRoute: typeof AdminNavigationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/discounts': {
      id: '/admin/discounts'
      path: '/discounts'
      fullPath: '/admin/discounts'
      preLoaderRoute: typeof AdminDiscountsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/colors': {
      id: '/admin/colors'
      path: '/colors'
      fullPath: '/admin/colors'
      preLoaderRoute: typeof AdminColorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_site/terms': {
      id: '/_site/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof SiteTermsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/shipping': {
      id: '/_site/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof SiteShippingRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/products': {
      id: '/_site/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof SiteProductsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/privacy': {
      id: '/_site/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof SitePrivacyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/faqs': {
      id: '/_site/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof SiteFaqsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/checkout': {
      id: '/_site/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof SiteCheckoutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/categories': {
      id: '/_site/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof SiteCategoriesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/cart': {
      id: '/_site/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof SiteCartRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/account': {
      id: '/_site/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof SiteAccountRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteAccountRoute: typeof SiteAccountRoute
  SiteCartRoute: typeof SiteCartRoute
  SiteCategoriesRoute: typeof SiteCategoriesRoute
  SiteCheckoutRoute: typeof SiteCheckoutRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteFaqsRoute: typeof SiteFaqsRoute
  SitePrivacyRoute: typeof SitePrivacyRoute
  SiteProductsRoute: typeof SiteProductsRoute
  SiteShippingRoute: typeof SiteShippingRoute
  SiteTermsRoute: typeof SiteTermsRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteAccountRoute: SiteAccountRoute,
  SiteCartRoute: SiteCartRoute,
  SiteCategoriesRoute: SiteCategoriesRoute,
  SiteCheckoutRoute: SiteCheckoutRoute,
  SiteContactRoute: SiteContactRoute,
  SiteFaqsRoute: SiteFaqsRoute,
  SitePrivacyRoute: SitePrivacyRoute,
  SiteProductsRoute: SiteProductsRoute,
  SiteShippingRoute: SiteShippingRoute,
  SiteTermsRoute: SiteTermsRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminColorsRoute: typeof AdminColorsRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDiscountsRoute: typeof AdminDiscountsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNavigationRoute: typeof AdminNavigationRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminColorsRoute: AdminColorsRoute,
  AdminContentRoute: AdminContentRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDiscountsRoute: AdminDiscountsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNavigationRoute: AdminNavigationRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
