// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// These are PUBLIC keys (anon/publishable) — safe to embed in client-side code.
// They are also read from environment variables when available (e.g. Vercel dashboard).
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ||
  (typeof process !== "undefined" && process.env?.SUPABASE_URL) ||
  "https://txhovpomafiomlfbegpx.supabase.co";

const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  (typeof process !== "undefined" && process.env?.SUPABASE_PUBLISHABLE_KEY) ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4aG92cG9tYWZpb21sZmJlZ3B4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc1NDEzMTUsImV4cCI6MjA5MzExNzMxNX0.OJhaN3dyGupd_4eQNQg7KGSewX95fx1SkJEBZUI5b2s";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== "undefined" ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  },
});

